name: Libertarianism
description: Philosopy of Freedom
url: https://www.libertarianism.info #place url
production_url: https://www.libertarianism.info
gems: [jekyll-paginate,jekyll-sitemap,jekyll-seo-tag]
baseurl: #place folder name if site is served in subfolder
permalink: /:title/
paginate: 8
paginate_path: /page/:num/
tag_dir: /tag
category_dir: /category
author_dir: /author
author_title_prefix: 'Posted by '
media_folder: /img
future: false
show_drafts: false
author_default_avatar: /profile-pic.jpg
seo_site_logo: https://www.libertarianism.info/Voluntarism_Logo.png
#pinterest: ""
#instagram: ""
twitter: 
  username: libertarianismX
facebook: 
  app_id: 142700499562936
  publisher: "https://www.facebook.com/libertarianism.info" #149433458884003
  admins: 100003950685739
social:
  name: libertarianism.info
  links: 
    - https://www.facebook.com/libertarianism.info
    - https://www.twitter.com/libertarianismX	
#youtube: ""
#vimeo: ""
#soundcloud: ""

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md]

# prose.io configurations
prose:
  media: "img"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          help: "display post at full width or with sidebar"
          options:
            - name: "with sidebar"
              value: "post"
            - name: "full width"
              value: "post_full"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          help: "author id as defined within _data/authors.yml"
          type: "text"
      - name: "featimg"
        field:
          element: "text"
          label: "Featured Image"
          help: "featured image within the img-folder"
          type: "text"
      - name: "type"
        field:
          element: "select"
          label: "Post Type"
          help: "each type has some special feature"
          options:
            - name: "Standard"
              value: "standard"
            - name: "Image"
              value: "image"
            - name: "Gallery"
              value: "gallery"
            - name: "Audio"
              value: "audio"
            - name: "YouTube"
              value: "youtube"
            - name: "Vimeo"
              value: "vimeo"
      - name: "homedisplay"
        field:
          element: "select"
          label: "Home Display"
          help: "decide whether to display embedded element (for post types: audio, youtube, vimeo) or Featured Image on home page"
          options:
            - name: "Featured Image"
              value: "featimg"
            - name: "Embedded Element"
              value: "iframe"
      - name: "vimeo-embed"
        field:
          element: "text"
          label: "Vimeo Embedding Code"
          help: "Set post type to vimeo in order for this to work"
      - name: "gallery-id"
        field:
          element: "text"
          label: "Gallery ID"
          help: "ID of the gallery defined within _data/galleries.yml - use include in content to use"
      - name: "audio-embed"
        field:
          element: "text"
          label: "Audio Embedding Code"
          help: "Set post type to audio in order for this to work"
      - name: "yt-video-id"
        field:
          element: "text"
          label: "YouTube Video ID"
          help: "Set post type to youtube in order for this to work. Do not set featured image, as the youtube video thumbnail will be used"
          type: "text"

